### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Proxymiity** [WeebDev/chibisafe#281]
**Describe the bug**
Uploads are not working when not logged in.

**To Reproduce**
1. Log out.
2. Upload a file.

**Expected behavior**
File uploads and a link is given.

**Screenshots**
[Video](https://f.iya.at/0sXEDu.mp4)
The file gets uploaded successfully:
![](https://i.iya.at/chrome_04SgLa.png)

**Additional context**
```
Jun 25 23:36:34 srv1.nya.network npm[7175]: Connection Error: Error: Packets out of order. Got: 0 Expected: 27
Jun 25 23:36:40 srv1.nya.network npm[7175]: (node:7296) UnhandledPromiseRejectionWarning: Error: Undefined binding(s) detected when compiling WHERE. Undefined column(s): [userId] query: where `userId` = ?
Jun 25 23:36:40 srv1.nya.network npm[7175]:     at QueryCompiler_MySQL.toSQL (/srv/chibisafe/node_modules/knex/lib/query/compiler.js:98:13)
Jun 25 23:36:40 srv1.nya.network npm[7175]:     at Formatter.compileCallback (/srv/chibisafe/node_modules/knex/lib/formatter.js:228:21)
Jun 25 23:36:40 srv1.nya.network npm[7175]:     at Formatter.rawOrFn (/srv/chibisafe/node_modules/knex/lib/formatter.js:167:36)
Jun 25 23:36:40 srv1.nya.network npm[7175]:     at QueryCompiler_MySQL.whereWrapped (/srv/chibisafe/node_modules/knex/lib/query/compiler.js:682:32)
Jun 25 23:36:40 srv1.nya.network npm[7175]:     at QueryCompiler_MySQL.where (/srv/chibisafe/node_modules/knex/lib/query/compiler.js:382:34)
Jun 25 23:36:40 srv1.nya.network npm[7175]:     at /srv/chibisafe/node_modules/knex/lib/query/compiler.js:115:69
Jun 25 23:36:40 srv1.nya.network npm[7175]:     at Array.map (<anonymous>)
Jun 25 23:36:40 srv1.nya.network npm[7175]:     at QueryCompiler_MySQL.select (/srv/chibisafe/node_modules/knex/lib/query/compiler.js:115:35)
Jun 25 23:36:40 srv1.nya.network npm[7175]:     at QueryCompiler_MySQL.toSQL (/srv/chibisafe/node_modules/knex/lib/query/compiler.js:61:29)
Jun 25 23:36:40 srv1.nya.network npm[7175]:     at Builder.toSQL (/srv/chibisafe/node_modules/knex/lib/query/builder.js:97:44)
Jun 25 23:36:40 srv1.nya.network npm[7175]: (Use `node --trace-warnings ...` to show where the warning was created)
Jun 25 23:36:40 srv1.nya.network npm[7175]: (node:7296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled witJun 25 23:36:40 srv1.nya.network npm[7175]: (node:7296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Jun 25 23:37:24 srv1.nya.network npm[7175]: (node:7296) UnhandledPromiseRejectionWarning: Error: Undefined binding(s) detected when compiling WHERE. Undefined column(s): [userId] query: where `userId` = ?
Jun 25 23:37:24 srv1.nya.network npm[7175]:     at QueryCompiler_MySQL.toSQL (/srv/chibisafe/node_modules/knex/lib/query/compiler.js:98:13)
Jun 25 23:37:24 srv1.nya.network npm[7175]:     at Formatter.compileCallback (/srv/chibisafe/node_modules/knex/lib/formatter.js:228:21)
Jun 25 23:37:24 srv1.nya.network npm[7175]:     at Formatter.rawOrFn (/srv/chibisafe/node_modules/knex/lib/formatter.js:167:36)
Jun 25 23:37:24 srv1.nya.network npm[7175]:     at QueryCompiler_MySQL.whereWrapped (/srv/chibisafe/node_modules/knex/lib/query/compiler.js:682:32)
Jun 25 23:37:24 srv1.nya.network npm[7175]:     at QueryCompiler_MySQL.where (/srv/chibisafe/node_modules/knex/lib/query/compiler.js:382:34)
Jun 25 23:37:24 srv1.nya.network npm[7175]:     at /srv/chibisafe/node_modules/knex/lib/query/compiler.js:115:69
Jun 25 23:37:24 srv1.nya.network npm[7175]:     at Array.map (<anonymous>)
Jun 25 23:37:24 srv1.nya.network npm[7175]:     at QueryCompiler_MySQL.select (/srv/chibisafe/node_modules/knex/lib/query/compiler.js:115:35)
Jun 25 23:37:24 srv1.nya.network npm[7175]:     at QueryCompiler_MySQL.toSQL (/srv/chibisafe/node_modules/knex/lib/query/compiler.js:61:29)
Jun 25 23:37:24 srv1.nya.network npm[7175]:     at Builder.toSQL (/srv/chibisafe/node_modules/knex/lib/query/builder.js:97:44)
Jun 25 23:37:24 srv1.nya.network npm[7175]: (node:7296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
```

**Comment by Pitu** [comment]
If this is a fresh installation, could you nuke it and start over at a certain commit?
To do so you would need to do
```sh
git clone https://github.com/WeebDev/chibisafe.git
git checkout 44cdb2a
```
And then run the setup instructions again.

Right now it seems that something is wrong with the master branch and I can't quite put my finger on it yet, so if you don't have files to lose this would be your best bet.

**Comment by Proxymiity** [comment]
I'll give it a shot tomorrow and keep ya updated!

**Comment by Proxymiity** [comment]
Still not working with `44cdb2a` :(

**Comment by Pitu** [comment]
I'm closing this since the new version was just pushed to master.
