### ISSUE TITLE
Error Right at the end of npm run setup

### ISSUE THREAD

**Issue by ajdlc** [WeebDev/chibisafe#302]
So, I am trying to install chibisafe on my Ubuntu server right now and when I run "npm run setup", select sqlite3 as my db, and finish the setup, I get presented with the following error:

chibisafe@4.0.2 migrate /home/aj/chibisafe
knex migrate:latest

/home/aj/chibisafe/src/api/utils/Util.js:18
	static uploadPath = path.join(__dirname, '../../../', 'uploads');
	                  ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/aj/chibisafe/src/api/database/migrations/20210112011802_addSettingsTable.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chibisafe@4.0.2 migrate: `knex migrate:latest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chibisafe@4.0.2 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aj/.npm/_logs/2021-10-29T05_10_55_292Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chibisafe@4.0.2 setup: `node src/setup.js && npm run migrate && npm run seed`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chibisafe@4.0.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aj/.npm/_logs/2021-10-29T05_10_55_317Z-debug.log

Any ideas? I can't seem to see what's wrong. I can grab that debug log as well if requested.

**Comment by ajdlc** [comment]
Wow, turns out I had version 10... I went ahead and upgraded to v17.0.1 and NPM version 8.1.0 and rebooted my server then ran all of the NPM commands and everything went smoothly. Sorry for the hassle! I didn't even think to check the NodeJS version!
