### ISSUE TITLE
Self signed certificate Error

### ISSUE THREAD

**Issue by DJPlaya** [WeebDev/chibisafe#308]
**Describe the bug**
Error related to SSL when connecting with either http or https.

In Webview:
```
Server error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
```

In CMD:
```
 Error occurred when calling nuxtServerInit:  self signed certificate
 ERROR  self signed certificate                                                                                    15:02:45

  at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
  at TLSSocket.emit (events.js:400:28)
  at TLSSocket.emit (domain.js:470:12)
  at TLSSocket._finishInit (_tls_wrap.js:936:8)
  at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12)
```

**To Reproduce**
1. Start with npm run start
2. Connect locally over http directly or over nginx/apache with either http or https

System:
Windows Server 2019
The certificate i have used in nginx/apache is self generated.

**Expected behavior**
Webpage showing

**Additional context**
Ive tried connecting to chibisafe either directly over http or by using nginx or apache with http or https.
Ive always run into the same error and couldent find any information on it so far.
I am not sure why there is an problem with selfmade certificates, ime planning to use chibisafe for personal use only and dont want to buy a real one.
Strangely, this error also appears when connecting to chibisafe directly with http, but not with https which results in an client sided "ERR_SSL_PROTOCOL_ERROR", so ime wondered.

**Comment by yesBad** [comment]
You know SSL Certs are free right?

**Comment by DJPlaya** [comment]
Depends, trusted Root Certification Authorities often want cash for their certs, so i have used OpenSSL to generate one for free.

**Comment by yesBad** [comment]
Can you show your Chibisafe .env file?

**Comment by DJPlaya** [comment]
DOMAIN=http://sls.sytes.com
SERVER_PORT=8080
DB_CLIENT=mysql
DB_HOST=127.0.0.1
DB_USER=local_sls
DB_PASSWORD=...
DB_DATABASE=local_sls

**Comment by yesBad** [comment]
> DOMAIN=http://sls.sytes.com SERVER_PORT=8080 DB_CLIENT=mysql DB_HOST=127.0.0.1 DB_USER=local_sls DB_PASSWORD=... DB_DATABASE=local_sls

and your NGINX config is?

**Comment by Aareksio** [comment]
^ + Does your instance work properly on `localhost:8080` without SSL on this config?

**Comment by DJPlaya** [comment]
@yesBad 
My config looks like this, it generates an https site only which is wanted. Ive changed it based on the example provided.
`
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    gzip  on;

upstream backend {
    server 127.0.0.1:8080;
}

server {
    listen 443 ssl http2 default;
    listen [::]:443 ssl http2 default;

    server_name sls.sytes.com:443;


    ssl_certificate C:/Users/Administrator/Desktop/Servers/nginx-1.20.1/server.crt;
    ssl_certificate_key C:/Users/Administrator/Desktop/Servers/nginx-1.20.1/server.key;
    ssl_trusted_certificate C:/Users/Administrator/Desktop/Servers/nginx-1.20.1/rootCA.pem;

    access_log C:/Users/Administrator/Desktop/Servers/nginx-1.20.1/domain.access.log;
    error_log C:/Users/Administrator/Desktop/Servers/nginx-1.20.1/domain.error.log;

    # Security
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-
    GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SH
    A:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM
    -SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
    ssl_prefer_server_ciphers on;
    add_header X-XSS-Protection "1; mode=block";
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;

    client_max_body_size 100M;
    client_body_timeout 600s;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://backend;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}}`

@Aareksio 
Accessing 8080 directly dosent work, and disabling ssl in nginx and redirecting straight http causes the mentioned error above in chibisafe

**Comment by Aareksio** [comment]
Considering accessing application port throws the SSL error, I suspect you made additional changes to the application config on top of what is suggested in [README](https://github.com/WeebDev/chibisafe#installing).

The application is supposed to process unencrypted HTTP traffic on port 8080. Only then you use nginx proxy as SSL termination point - nginx decodes SSL traffic and passes non-SSL traffic to node application running on 8080 along with `X-Forwarded-Proto: https` to let it know about the SSL termination.

Please use fresh clone (preferably) or revert any changes you made, especially those to `nuxt.config.js`, `src/api/structures/Server.js`. Once the HTTP response on 8080 is achieved, the nxing config you pasted should do the work.

**Comment by DJPlaya** [comment]
@Aareksio 
After cloning and setting up again i received the same error when connecting directly.
I also ran npm setup again with sqlite for a test, but same results.
I have Node.js 14.17.4 and all dependencys should be fresh too.
The only thing i dont have is pm2, but that shouldent be a problem?

**Comment by Aareksio** [comment]
I do not have any other ideas then. You can try upgrading to node 16, which is active LTS as of this month. I'd also suggest trying the setup on different than Windows Server system - the underlying system might be the reason for the errors you are facing.

**Comment by AruMoon** [comment]
> I do not have any other ideas then. You can try upgrading to node 16, which is active LTS as of this month. I'd also suggest trying the setup on different than Windows Server system - the underlying system might be the reason for the errors you are facing.

node-sass v5 doesn't work on node 16

**Comment by Aareksio** [comment]
> node-sass v5 doesn't work on node 16
<https://github.com/WeebDev/chibisafe/issues/309#issuecomment-970303229>

It's a wild guess node 16 may help - perhaps they fixed something on Windows

**Comment by Pitu** [comment]
`node-sass` will be removed as a dependency in favor of `dart-sass` that doesn't need to be compiled, which has always been a problem for the former.
